name: CrawlAndPublish

on:
  push:
    branches:
    - crawled-data

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: setup ubuntu
      run: sudo apt --quiet update --yes
    - name: install to need
      run: sudo apt --quiet install git libmysqlclient-dev mecab libmecab-dev mecab-ipadic-utf8 --yes
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3
    - name: Bundle install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Register .env
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_BOT_ACCESS_TOKEN: ${{ secrets.TWITTER_BOT_ACCESS_TOKEN }}
        TWITTER_BOT_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_BOT_ACCESS_TOKEN_SECRET }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
        GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
        GOOGLE_OAUTH_BOT_REFRESH_TOKEN: ${{ secrets.GOOGLE_OAUTH_BOT_REFRESH_TOKEN }}
        QIITA_BOT_ACCESS_TOKEN: ${{ secrets.QIITA_BOT_ACCESS_TOKEN }}
        MEETUP_API_KEY: ${{ secrets.MEETUP_API_KEY }}
        BITLY_ACCESS_TOKEN: ${{ secrets.BITLY_ACCESS_TOKEN }}
      run: |
        echo "MYSQL_USERNAME='root'" >> ./.env
        echo "MYSQL_PASSWORD='root'" >> ./.env
        echo "TWITTER_CONSUMER_KEY='${TWITTER_CONSUMER_KEY}'" >> ./.env
        echo "TWITTER_CONSUMER_SECRET='${TWITTER_CONSUMER_SECRET}'" >> ./.env
        echo "TWITTER_BOT_ACCESS_TOKEN='${TWITTER_BOT_ACCESS_TOKEN}'" >> ./.env
        echo "TWITTER_BOT_ACCESS_TOKEN_SECRET='${TWITTER_BOT_ACCESS_TOKEN_SECRET}'" >> ./.env
        echo "GOOGLE_API_KEY='${GOOGLE_API_KEY}'" >> ./.env
        echo "GOOGLE_OAUTH_CLIENT_ID='${GOOGLE_OAUTH_CLIENT_ID}'" >> ./.env
        echo "GOOGLE_OAUTH_CLIENT_SECRET='${GOOGLE_OAUTH_CLIENT_SECRET}'" >> ./.env
        echo "GOOGLE_OAUTH_BOT_REFRESH_TOKEN='${GOOGLE_OAUTH_BOT_REFRESH_TOKEN}'" >> ./.env
        echo "QIITA_BOT_ACCESS_TOKEN='${QIITA_BOT_ACCESS_TOKEN}'" >> ./.env
        echo "MEETUP_API_KEY='${MEETUP_API_KEY}'" >> ./.env
        echo "BITLY_ACCESS_TOKEN='${BITLY_ACCESS_TOKEN}'" >> ./.env
    - name: MySQL db create
      run: |
        RAILS_ENV=production rails db:create
    - name: MySQL db migrate
      run: |
        RAILS_ENV=production rails db:migrate
    - name: MySQL db seed
      run: |
        RAILS_ENV=production rails db:seed
    - name: Install Mecab Neologd
      working-directory: ./tmp
      run: |
        git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git
        ./mecab-ipadic-neologd/bin/install-mecab-ipadic-neologd -n -y --eliminate-redundant-entry
    - name: export dbdump
      run: |
        RAILS_ENV=production rails backup:export_active_records_data
    - name: Commit files
      env:
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_NAME: ${{ secrets.USER_NAME }}
      run: |
        git config --local user.email "${USER_EMAIL}"
        git config --local user.name "${USER_NAME}"
        git commit -m "add `date +%Y-%m-%d-%H:%M:%S` crawled data" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        branch: 'crawled-data'
    - uses: actions/upload-artifact@master
      with:
        name: log
        path: log