name: CrawlAndPublish

on:
  schedule:
    - cron: 00 1 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        volumes: data:/db_volume
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_USER: "root"
          MYSQL_PASSWORD: ""
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    steps:
    - uses: actions/checkout@v1
    - name: setup ubuntu
      run: sudo apt-get --quiet update --yes
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3
    - name: Bundle install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: MySQL db create
      run: |
        RAILS_ENV=production rails db:create
    - name: MySQL db migrate
      run: |
        RAILS_ENV=production rails db:migrate
    - name: MySQL db seed
      run: |
        RAILS_ENV=production rails db:seed
    - name: Register .env
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_BOT_ACCESS_TOKEN: ${{ secrets.TWITTER_BOT_ACCESS_TOKEN }}
        TWITTER_BOT_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_BOT_ACCESS_TOKEN_SECRET }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
        GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
        GOOGLE_OAUTH_BOT_REFRESH_TOKEN: ${{ secrets.GOOGLE_OAUTH_BOT_REFRESH_TOKEN }}
        MEETUP_API_KEY: ${{ secrets.MEETUP_API_KEY }}
        BITLY_ACCESS_TOKEN: ${{ secrets.BITLY_ACCESS_TOKEN }}
      run: |
        echo "TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}" >> ./.env
        echo "TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}" >> ./.env
        echo "TWITTER_BOT_ACCESS_TOKEN=${TWITTER_BOT_ACCESS_TOKEN}" >> ./.env
        echo "TWITTER_BOT_ACCESS_TOKEN_SECRET=${TWITTER_BOT_ACCESS_TOKEN_SECRET}" >> ./.env
        echo "GOOGLE_API_KEY=${GOOGLE_API_KEY}" >> ./.env
        echo "GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}" >> ./.env
        echo "GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}" >> ./.env
        echo "GOOGLE_OAUTH_BOT_REFRESH_TOKEN=${GOOGLE_OAUTH_BOT_REFRESH_TOKEN}" >> ./.env
        echo "MEETUP_API_KEY=${MEETUP_API_KEY}" >> ./.env
        echo "BITLY_ACCESS_TOKEN=${BITLY_ACCESS_TOKEN}" >> ./.env
    - name: execute crawl
      run: |
        rails batch:event_crawl
    - name: export dbdump
      run: |
        mysqldump -u root hackathon_portal_production --no-create-info -c --order-by-primary --skip-extended-insert --skip-add-locks --skip-comments --compact > hackathon_portal_production.sql
    - name: reconstruct split dbdump
      run: |
        rm -r ./db/seeds/
        mkdir ./db/seeds/
        split -l 10000 -d --additional-suffix=.sql hackathon_portal_production.sql ./db/seeds/
    - name: git commit and push
      run: |
        rails backup:cd_git_commit_and_push